DROP TABLE IF EXISTS CELL;

CREATE TABLE CELL (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  LATITUDE DOUBLE NOT NULL,
  LONGITUDE DOUBLE NOT NULL,
  TIMESTAMP_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  POWER DOUBLE ,
  RADIUS DOUBLE 
);

DROP TABLE IF EXISTS CELL_WITH_POWER;
CREATE TABLE CELL_WITH_POWER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  POWER DOUBLE ,
  RADIUS DOUBLE 
);
DROP TABLE IF EXISTS CELL_WITH_RADIUS;

CREATE TABLE CELL_WITH_RADIUS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  RADIUS DOUBLE 
);


DROP TABLE IF EXISTS CELL_EVENT;
CREATE TABLE CELL_EVENT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,/*MANCA VINCOLO DI INTEGRITA' REFERENZIALE, NON SO LA SINTASSI IN H2*/
  TYPOLOGY VARCHAR(30) NOT NULL,
  TIMESTAMP_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  TIMESTAMP_EVENT TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);