INSERT INTO CELL (ID ,NAME, LATITUDE,LONGITUDE,TIMESTAMP_CREATION) 
VALUES (1, 'origin',0 ,0, CURRENT_TIMESTAMP);

INSERT INTO CELL (ID ,NAME, LATITUDE,LONGITUDE,TIMESTAMP_CREATION) 
VALUES (2, 'cell1', 45.4616873,9.0756298, CURRENT_TIMESTAMP);

INSERT INTO CELL (ID ,NAME, LATITUDE,LONGITUDE,TIMESTAMP_CREATION) 
VALUES (3, 'cell2', 45.4732446,9.0961433, CURRENT_TIMESTAMP);


INSERT INTO CELL_EVENT (ID, TYPOLOGY , TIMESTAMP_CREATION,TIMESTAMP_EVENT)
VALUES(1, 'CONNECTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
  
INSERT INTO CELL_EVENT (ID, TYPOLOGY , TIMESTAMP_CREATION,TIMESTAMP_EVENT)
VALUES(2, 'CONNECTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO CELL_EVENT (ID, TYPOLOGY , TIMESTAMP_CREATION,TIMESTAMP_EVENT)
VALUES(3, 'DISCONNECTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

